select `user_pseudo_id`,
    `event_date`,
    `event_name`,
    `source`,
    `medium`,
    `campaign`,
    `category`,
    `language`,
    `operator`,
    `revenue`,
    `page_path`
from 
(
    SELECT 
    user_pseudo_id,
    event_date,
    event_name,
    traffic_source.source AS source,
    traffic_source.medium AS medium,
    traffic_source.name AS campaign,
    device.category as category,
    device.language as language,
    device.operating_system as operator,
   (SELECT COALESCE(value.double_value, value.float_value) FROM UNNEST(event_params) WHERE key = 'value') AS revenue, 
   (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'page_location') AS page_path
    from `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
where event_name in (
  'session_start',
  'view_item', 
  'add_to_cart',
  'begin_checkout',
  'add_shipping_info',
  'add_payment_info',
  'purchase'
)
) as `_`
LIMIT 1000 OFFSET 0